/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.clock;

/**
 *
 * @author vital
 */
public class ViewAllClocks extends javax.swing.JPanel implements IObserver {

    /**
     * Creates new form ViewAllClocks
     */
    public ViewAllClocks() {
        initComponents();
        
        BCollectionClock.build().sub(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        allClocks = new javax.swing.JPanel();

        allClocks.setLayout(new java.awt.GridLayout(0, 1));
        jScrollPane1.setViewportView(allClocks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allClocks;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void event(CollectionClock colClock) {
        allClocks.removeAll();
        
        for (IClock clock : colClock) {
            ClockPanel cPanel = new ClockPanel();
            cPanel.setClock(clock);
            allClocks.add(cPanel);
        }
        jScrollPane1.validate();
    }




}

